package viewer.admin;

import java.sql.SQLException;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;

import control.Controller;
import launcher.Main;
import model.Doctor;

/**
 *
 * @author rodri
 */

@SuppressWarnings("serial")
public class DoctorPatientsPanel extends javax.swing.JPanel{

	private static DoctorPatientsPanel instance = null;

	private Vector<Doctor> doctorList;
	private PatientsofDoctorTable patientsofDoctorTable;
	private Doctor doctor;


	private DoctorPatientsPanel(Controller ctrl) {
		doctorList = ctrl.getDoctorList();

		patientsofDoctorTable = new PatientsofDoctorTable(ctrl);
		initComponents();
	}

	public static DoctorPatientsPanel getInstace(Controller ctrl) {
		if (instance == null)
			instance = new DoctorPatientsPanel(ctrl);
		instance.open();

		return instance;
	}

	private void open() {
		doctor = (Doctor) doctorComboBox.getSelectedItem();
		try {
			patientsofDoctorTable.open(doctor.getDni());
		} catch (SQLException e) {
			//TODO dialogo de error
			if(Main.SHOW_EXCEPTIONS_TRACE)
				e.printStackTrace();
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		TopPanel = new javax.swing.JPanel();
		SelectDoctorPanel = new javax.swing.JPanel();
		LabelPanel = new javax.swing.JPanel();
		doctorLabel = new javax.swing.JLabel();
		ComboBoxPanel = new javax.swing.JPanel();
		doctorComboBox = new javax.swing.JComboBox<>();
		CenterPanel = new javax.swing.JPanel();
		showPatientsButton = new misc.RSButtonMetro();
		TablePanel = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setLayout(new java.awt.BorderLayout());

		TopPanel.setLayout(new javax.swing.BoxLayout(TopPanel, javax.swing.BoxLayout.Y_AXIS));

		SelectDoctorPanel.setLayout(new javax.swing.BoxLayout(SelectDoctorPanel, javax.swing.BoxLayout.Y_AXIS));

		LabelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));

		doctorLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		doctorLabel.setForeground(new java.awt.Color(51, 51, 51));
		doctorLabel.setText("Select a doctor");
		LabelPanel.add(doctorLabel);

		SelectDoctorPanel.add(LabelPanel);

		ComboBoxPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));

		doctorComboBox.setModel(new DefaultComboBoxModel<>(doctorList));
		ComboBoxPanel.add(doctorComboBox);

		SelectDoctorPanel.add(ComboBoxPanel);

		TopPanel.add(SelectDoctorPanel);

		CenterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));

		showPatientsButton.setText("Show Patients");
		showPatientsButton.setColorHover(new java.awt.Color(138, 202, 234));
		showPatientsButton.setColorNormal(new java.awt.Color(8, 72, 135));
		showPatientsButton.setColorPressed(new java.awt.Color(8, 72, 135));
		showPatientsButton.setColorTextHover(new java.awt.Color(51, 51, 51));
		showPatientsButton.setColorTextNormal(new java.awt.Color(242, 242, 242));
		showPatientsButton.setColorTextPressed(new java.awt.Color(242, 242, 242));
		showPatientsButton.setFocusPainted(false);
		showPatientsButton.setRolloverEnabled(false);
		showPatientsButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showPatientsButtonActionPerformed(evt);
			}
		});
		CenterPanel.add(showPatientsButton);

		TopPanel.add(CenterPanel);

		add(TopPanel, java.awt.BorderLayout.PAGE_START);

		jTable1.setModel(patientsofDoctorTable);
		TablePanel.setViewportView(jTable1);

		add(TablePanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>

	private void showPatientsButtonActionPerformed(java.awt.event.ActionEvent evt) {
		open();
	}


	// Variables declaration - do not modify
	private javax.swing.JPanel CenterPanel;
	private javax.swing.JPanel ComboBoxPanel;
	private javax.swing.JPanel LabelPanel;
	private javax.swing.JPanel SelectDoctorPanel;
	private javax.swing.JScrollPane TablePanel;
	private javax.swing.JPanel TopPanel;
	private javax.swing.JLabel doctorLabel;
	private javax.swing.JComboBox<Doctor> doctorComboBox;
	private javax.swing.JTable jTable1;
	private misc.RSButtonMetro showPatientsButton;
	// End of variables declaration
}
