package viewer.admin;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import control.Controller;
import launcher.Main;
import model.Doctor;
import model.Patient;

/**
 *
 * @author rodri
 */
public class DoctorModPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DoctorModPanel
	 */
	private static DoctorModPanel instance = null;

	private Controller ctrl;
	private Vector<Doctor> doctorList;
	private List<String> info;

	private DoctorModPanel(Controller ctrl) {
		this.ctrl = ctrl;
		initComponents();
	}

	// Singleton
	public static DoctorModPanel getInstace(Controller ctrl) {
		if (instance == null)
			instance = new DoctorModPanel(ctrl);
		instance.open();

		return instance;
	}

	private void open() {
		doctorList = ctrl.getDoctorList();
		doctorComboBox.setModel(new DefaultComboBoxModel<>(doctorList));
		updateDoctorInfo();
	}

	private void updateDoctorInfo() {
		try {
			info = ctrl.getDoctorData(((Doctor) doctorComboBox.getSelectedItem()).getDni()).asStringList();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), e.getMessage(), "", JOptionPane.ERROR_MESSAGE);
			if(Main.SHOW_EXCEPTIONS_TRACE)
				e.printStackTrace();
		}
		textName.setText(info.get(2));
		textLastName.setText(info.get(1));
		textBDay.setText(info.get(3));
		textemail.setText(info.get(4));
		textPhone.setText(info.get(5));
		textSpeciality.setText(info.get(6));
		textSalary.setText(info.get(7));
		textStart.setText(info.get(8));
		textEnd.setText(info.get(9));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		northPanel = new javax.swing.JPanel();
		LabelPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		ComboBoxPanel = new javax.swing.JPanel();
		doctorComboBox = new javax.swing.JComboBox<>();
		ButtonUpdatePanel = new javax.swing.JPanel();
		buttonUpdate = new misc.RSButtonMetro();
		centerlPanel = new javax.swing.JPanel();
		NamePanel = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		textName = new javax.swing.JTextField();
		LastNamePanel = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		textLastName = new javax.swing.JTextField();
		BithDatePanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		textBDay = new javax.swing.JTextField();
		EmailPanel = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		textemail = new javax.swing.JTextField();
		EmailPanel1 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		textPhone = new javax.swing.JTextField();
		EmailPanel2 = new javax.swing.JPanel();
		jLabel20 = new javax.swing.JLabel();
		textSpeciality = new javax.swing.JTextField();
		EmailPanel3 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		textSalary = new javax.swing.JTextField();
		EmailPanel4 = new javax.swing.JPanel();
		jLabel22 = new javax.swing.JLabel();
		textStart = new javax.swing.JTextField();
		EmailPanel5 = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		textEnd = new javax.swing.JTextField();
		ButtonsPanel = new javax.swing.JPanel();
		buttonsave = new misc.RSButtonMetro();


		setLayout(new java.awt.BorderLayout());

		northPanel.setLayout(new javax.swing.BoxLayout(northPanel, javax.swing.BoxLayout.Y_AXIS));

		LabelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		jLabel1.setText("Select a doctor");
		LabelPanel.add(jLabel1);

		northPanel.add(LabelPanel);

		doctorList = new Vector<>();
		doctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(doctorList));
		ComboBoxPanel.add(doctorComboBox);

		northPanel.add(ComboBoxPanel);

		buttonUpdate.setText("Update");
		buttonUpdate.setColorHover(new java.awt.Color(138, 202, 234));
		buttonUpdate.setColorNormal(new java.awt.Color(8, 72, 135));
		buttonUpdate.setColorPressed(new java.awt.Color(8, 72, 135));
		buttonUpdate.setColorTextHover(new java.awt.Color(51, 51, 51));
		buttonUpdate.setColorTextNormal(new java.awt.Color(242, 242, 242));
		buttonUpdate.setColorTextPressed(new java.awt.Color(242, 242, 242));
		buttonUpdate.setFocusPainted(false);
		buttonUpdate.setRolloverEnabled(false);
		buttonUpdate.setRolloverEnabled(false);
		buttonUpdate.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				buttonUpdateActionPerformed(e);
			}
		});

		ButtonUpdatePanel.add(buttonUpdate);

		northPanel.add(ButtonUpdatePanel);

		add(northPanel, java.awt.BorderLayout.PAGE_START);

		centerlPanel.setLayout(new javax.swing.BoxLayout(centerlPanel, javax.swing.BoxLayout.Y_AXIS));

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(51, 51, 51));
		jLabel10.setText("Name: ");
		NamePanel.add(jLabel10);

		textName.setText("jTextField1");
		textName.setPreferredSize(new Dimension(120, 20));
		NamePanel.add(textName);

		centerlPanel.add(NamePanel);

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(51, 51, 51));
		jLabel11.setText("Last Name: ");
		LastNamePanel.add(jLabel11);

		textLastName.setText("jTextField1");
		textLastName.setPreferredSize(new Dimension(120, 20));
		LastNamePanel.add(textLastName);

		centerlPanel.add(LastNamePanel);

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(51, 51, 51));
		jLabel12.setText("Birth Date: ");
		BithDatePanel.add(jLabel12);

		textBDay.setText("jTextField1");
		textBDay.setPreferredSize(new Dimension(120, 20));
		BithDatePanel.add(textBDay);

		centerlPanel.add(BithDatePanel);

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(51, 51, 51));
		jLabel13.setText("Email: ");
		EmailPanel.add(jLabel13);

		textemail.setText("jTextField1");
		textemail.setPreferredSize(new Dimension(120, 20));
		EmailPanel.add(textemail);

		centerlPanel.add(EmailPanel);

		jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(51, 51, 51));
		jLabel19.setText("Phone: ");
		EmailPanel1.add(jLabel19);

		textPhone.setText("jTextField1");
		textPhone.setPreferredSize(new Dimension(120, 20));
		EmailPanel1.add(textPhone);

		centerlPanel.add(EmailPanel1);

		jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel20.setForeground(new java.awt.Color(51, 51, 51));
		jLabel20.setText("Speciality: ");
		EmailPanel2.add(jLabel20);

		textSpeciality.setText("jTextField1");
		textSpeciality.setPreferredSize(new Dimension(120, 20));
		EmailPanel2.add(textSpeciality);

		centerlPanel.add(EmailPanel2);

		jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(51, 51, 51));
		jLabel21.setText("Salary: ");
		EmailPanel3.add(jLabel21);

		textSalary.setText("jTextField1");
		textSalary.setPreferredSize(new Dimension(120, 20));
		EmailPanel3.add(textSalary);

		centerlPanel.add(EmailPanel3);

		jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel22.setForeground(new java.awt.Color(51, 51, 51));
		jLabel22.setText("Start Date: ");
		EmailPanel4.add(jLabel22);

		textStart.setText("jTextField1");
		textStart.setPreferredSize(new Dimension(120, 20));
		EmailPanel4.add(textStart);

		centerlPanel.add(EmailPanel4);

		jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel23.setForeground(new java.awt.Color(51, 51, 51));
		jLabel23.setText("End Date:");
		EmailPanel5.add(jLabel23);

		textEnd.setText("jTextField1");
		textEnd.setPreferredSize(new Dimension(120, 20));
		EmailPanel5.add(textEnd);

		centerlPanel.add(EmailPanel5);

		buttonsave.setText("Save");
		buttonsave.setColorHover(new java.awt.Color(138, 202, 234));
		buttonsave.setColorNormal(new java.awt.Color(8, 72, 135));
		buttonsave.setColorPressed(new java.awt.Color(8, 72, 135));
		buttonsave.setColorTextHover(new java.awt.Color(51, 51, 51));
		buttonsave.setColorTextNormal(new java.awt.Color(242, 242, 242));
		buttonsave.setColorTextPressed(new java.awt.Color(242, 242, 242));
		buttonsave.setFocusPainted(false);
		buttonsave.setRolloverEnabled(false);
		buttonsave.setRolloverEnabled(false);
		buttonsave.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				buttonsaveActionPerformed(e);
			}
		});
		ButtonsPanel.add(buttonsave);

		centerlPanel.add(ButtonsPanel);

		add(centerlPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>

	private void buttonUpdateActionPerformed(ActionEvent e) {
		updateDoctorInfo();
	}

	private void buttonsaveActionPerformed(ActionEvent e) {
		List<String> colData = getIntroducedData();
		if (colData.size() != 10) {
			JOptionPane.showMessageDialog(null, "Not enough arguments",
					"Error on data collection", JOptionPane.ERROR_MESSAGE);
		}
		else {
			try {
				ctrl.updateDoctor(colData);
				JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Changes were saved sucessfully","", JOptionPane.INFORMATION_MESSAGE);
			} catch (SQLException e1) {
				JOptionPane.showMessageDialog(null, e1.getMessage(), "Error on Query", JOptionPane.ERROR_MESSAGE);
				if (Main.SHOW_EXCEPTIONS_TRACE)
					e1.printStackTrace();
			}
		}
	}

	public List<String> getIntroducedData(){
		ArrayList<String> data = new ArrayList<String>();
		data.add(((Patient) doctorComboBox.getSelectedItem()).getDni());
		data.add(textLastName.getText());
		data.add(textName.getText());
		data.add(textBDay.getText());
		data.add(textemail.getText());
		data.add(textPhone.getText());
		data.add(textSpeciality.getText());
		data.add(textSalary.getText());
		data.add(textStart.getText());
		data.add(textEnd.getText());
		return data;
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel BithDatePanel;
	private javax.swing.JPanel ButtonsPanel;
	private misc.RSButtonMetro buttonsave;
	private misc.RSButtonMetro buttonUpdate;
	private javax.swing.JPanel ButtonUpdatePanel;
	private javax.swing.JPanel ComboBoxPanel;
	private javax.swing.JPanel EmailPanel;
	private javax.swing.JPanel EmailPanel1;
	private javax.swing.JPanel EmailPanel2;
	private javax.swing.JPanel EmailPanel3;
	private javax.swing.JPanel EmailPanel4;
	private javax.swing.JPanel EmailPanel5;
	private javax.swing.JPanel LabelPanel;
	private javax.swing.JPanel LastNamePanel;
	private javax.swing.JPanel NamePanel;
	private javax.swing.JPanel centerlPanel;
	private javax.swing.JComboBox<Doctor> doctorComboBox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JTextField textEnd;
	private javax.swing.JTextField textName;
	private javax.swing.JTextField textLastName;
	private javax.swing.JTextField textBDay;
	private javax.swing.JTextField textemail;
	private javax.swing.JTextField textPhone;
	private javax.swing.JTextField textSpeciality;
	private javax.swing.JTextField textSalary;
	private javax.swing.JTextField textStart;
	private javax.swing.JPanel northPanel;
	// End of variables declaration
}

