package viewer.admin;

import java.util.List;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;

import control.Controller;
import model.Patient;
import model.Enums.BloodType;
import model.Enums.Gender;
import model.Enums.HealthInsuranceType;

/**
 *
 * @author rodri
 */
public class PacientModPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DoctorModPanel
	 */
	private Controller ctrl;
	// dni, lastname,name, birthdate, email, phone, gender, blood_type, insurance_type, dni_insurance_taker, bill
	private Vector<Patient> patientList;
	private List<String> info;
	private Patient patient;

	public PacientModPanel(Controller ctrl) {
		this.ctrl = ctrl;
		patientList = ctrl.getAllPatients();
		initComponents();

	}

	void open() {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		NorthPanel = new javax.swing.JPanel();
		LabelPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		ComboBoxPanel = new javax.swing.JPanel();
		patientComboBox = new javax.swing.JComboBox<>();
		CenterPanel = new javax.swing.JPanel();
		NamePanel = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		LastNamePanel = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		BithDatePanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		EmailPanel = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		EmailPanel1 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		GenderPanel = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		BloodTypePanel = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox<>();
		InsuranceTypePanel = new javax.swing.JPanel();
		jLabel16 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox<>();
		InsuranceTakerPanel = new javax.swing.JPanel();
		jLabel17 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		BillPanel = new javax.swing.JPanel();
		jLabel18 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		ButtonsPanel = new javax.swing.JPanel();
		cancel = new misc.RSButtonMetro();
		commit = new misc.RSButtonMetro();

		setLayout(new java.awt.BorderLayout());

		NorthPanel.setLayout(new javax.swing.BoxLayout(NorthPanel, javax.swing.BoxLayout.Y_AXIS));

		LabelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		jLabel1.setText("Select a doctor");
		LabelPanel.add(jLabel1);

		NorthPanel.add(LabelPanel);

		patientComboBox.setModel(new DefaultComboBoxModel<>(patientList));
		Patient p = (Patient) patientComboBox.getSelectedItem();
		info = ctrl.getPatientData(p.getDni()).asStringList();
		ComboBoxPanel.add(patientComboBox);

		NorthPanel.add(ComboBoxPanel);

		add(NorthPanel, java.awt.BorderLayout.PAGE_START);

		CenterPanel.setLayout(new javax.swing.BoxLayout(CenterPanel, javax.swing.BoxLayout.Y_AXIS));

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(51, 51, 51));
		jLabel10.setText("Name: ");
		NamePanel.add(jLabel10);

		jTextField2.setText("jTextField1");
		NamePanel.add(jTextField2);

		CenterPanel.add(NamePanel);

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(51, 51, 51));
		jLabel11.setText("Last Name: ");
		LastNamePanel.add(jLabel11);

		jTextField3.setText("jTextField1");
		LastNamePanel.add(jTextField3);

		CenterPanel.add(LastNamePanel);

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(51, 51, 51));
		jLabel12.setText("Birth Date: ");
		BithDatePanel.add(jLabel12);

		jTextField4.setText("jTextField1");
		BithDatePanel.add(jTextField4);

		CenterPanel.add(BithDatePanel);

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(51, 51, 51));
		jLabel13.setText("Email: ");
		EmailPanel.add(jLabel13);

		jTextField5.setText("jTextField1");
		EmailPanel.add(jTextField5);

		CenterPanel.add(EmailPanel);

		jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(51, 51, 51));
		jLabel19.setText("Phone: ");
		EmailPanel1.add(jLabel19);

		jTextField6.setText("jTextField1");
		EmailPanel1.add(jTextField6);

		CenterPanel.add(EmailPanel1);

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(51, 51, 51));
		jLabel14.setText("Gender: ");
		GenderPanel.add(jLabel14);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Gender.values()));
		GenderPanel.add(jComboBox1);

		CenterPanel.add(GenderPanel);

		jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(51, 51, 51));
		jLabel15.setText("Blood Type: ");
		BloodTypePanel.add(jLabel15);

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(BloodType.values()));
		BloodTypePanel.add(jComboBox2);

		CenterPanel.add(BloodTypePanel);

		jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(51, 51, 51));
		jLabel16.setText("Insurance Type: ");
		InsuranceTypePanel.add(jLabel16);

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(HealthInsuranceType.values()));
		InsuranceTypePanel.add(jComboBox3);

		CenterPanel.add(InsuranceTypePanel);

		jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel17.setForeground(new java.awt.Color(51, 51, 51));
		jLabel17.setText("Insurance Taker: ");
		InsuranceTakerPanel.add(jLabel17);

		jTextField9.setText("jTextField1");
		InsuranceTakerPanel.add(jTextField9);

		CenterPanel.add(InsuranceTakerPanel);

		jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(51, 51, 51));
		jLabel18.setText("Bill");
		BillPanel.add(jLabel18);

		jTextField10.setText("jTextField1");
		BillPanel.add(jTextField10);

		CenterPanel.add(BillPanel);

		cancel.setText("Cancel");
		cancel.setColorHover(new java.awt.Color(138, 202, 234));
		cancel.setColorNormal(new java.awt.Color(8, 72, 135));
		cancel.setColorPressed(new java.awt.Color(8, 72, 135));
		cancel.setColorTextHover(new java.awt.Color(51, 51, 51));
		cancel.setColorTextNormal(new java.awt.Color(242, 242, 242));
		cancel.setColorTextPressed(new java.awt.Color(242, 242, 242));
		cancel.setFocusPainted(false);
		cancel.setRolloverEnabled(false);
		cancel.setRolloverEnabled(false);
		ButtonsPanel.add(cancel);

		commit.setText("Commit");
		commit.setColorHover(new java.awt.Color(138, 202, 234));
		commit.setColorNormal(new java.awt.Color(8, 72, 135));
		commit.setColorPressed(new java.awt.Color(8, 72, 135));
		commit.setColorTextHover(new java.awt.Color(51, 51, 51));
		commit.setColorTextNormal(new java.awt.Color(242, 242, 242));
		commit.setColorTextPressed(new java.awt.Color(242, 242, 242));
		commit.setFocusPainted(false);
		commit.setRolloverEnabled(false);
		ButtonsPanel.add(commit);

		CenterPanel.add(ButtonsPanel);

		add(CenterPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>


	// Variables declaration - do not modify
	private javax.swing.JPanel BillPanel;
	private javax.swing.JPanel BithDatePanel;
	private javax.swing.JPanel BloodTypePanel;
	private javax.swing.JPanel ButtonsPanel;
	private javax.swing.JPanel CenterPanel;
	private javax.swing.JPanel ComboBoxPanel;
	private javax.swing.JPanel EmailPanel;
	private javax.swing.JPanel EmailPanel1;
	private javax.swing.JPanel GenderPanel;
	private javax.swing.JPanel InsuranceTakerPanel;
	private javax.swing.JPanel InsuranceTypePanel;
	private javax.swing.JPanel LabelPanel;
	private javax.swing.JPanel LastNamePanel;
	private javax.swing.JPanel NamePanel;
	private javax.swing.JPanel NorthPanel;
	private misc.RSButtonMetro cancel;
	private misc.RSButtonMetro commit;
	private javax.swing.JComboBox<Patient> patientComboBox;
	private javax.swing.JComboBox<Gender> jComboBox1;
	private javax.swing.JComboBox<BloodType> jComboBox2;
	private javax.swing.JComboBox<HealthInsuranceType> jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration

}