package viewer.admin;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import control.Controller;
import launcher.Main;
import model.Patient;
import model.Enums.BloodType;
import model.Enums.Gender;
import model.Enums.HealthInsuranceType;

/**
 *
 * @author rodri
 */
public class PacientModPanel extends javax.swing.JPanel {

	/**
	 * Creates new form DoctorModPanel
	 */
	private Controller ctrl;
	// dni, lastname,name, birthdate, email, phone, gender, blood_type, insurance_type, dni_insurance_taker, bill
	private Vector<Patient> patientList;
	private List<String> info;
	private Patient patient;

	public PacientModPanel(Controller ctrl) {
		this.ctrl = ctrl;
		patientList = ctrl.getAllPatients();
		initComponents();

	}

	void open() {
		patient = (Patient) patientComboBox.getSelectedItem();
		info = ctrl.getPatientData(patient.getDni()).asStringList();
		textName.setText(info.get(2));
		textLastName.setText(info.get(1));
		textBDay.setText(info.get(3));
		textemail.setText(info.get(4));
		textPhone.setText(info.get(5));
		textGender.setSelectedItem(Gender.valueOf(info.get(6)));
		bloodText.setSelectedItem(BloodType.getEnum(info.get(7)));
		textGender.setSelectedItem(HealthInsuranceType.valueOf(info.get(8)));
		takerText.setText(info.get(9) == null ? patient.getDni() : info.get(9));
		billText.setText(info.get(10) == null ? "0.000" : info.get(10));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		NorthPanel = new javax.swing.JPanel();
		LabelPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		ComboBoxPanel = new javax.swing.JPanel();
		patientComboBox = new javax.swing.JComboBox<>();
		ButtonUpdatePanel = new javax.swing.JPanel();
		buttonUpdate = new misc.RSButtonMetro();
		CenterPanel = new javax.swing.JPanel();
		NamePanel = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		textName = new javax.swing.JTextField();
		LastNamePanel = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		textLastName = new javax.swing.JTextField();
		BithDatePanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		textBDay = new javax.swing.JTextField();
		EmailPanel = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		textemail = new javax.swing.JTextField();
		EmailPanel1 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		textPhone = new javax.swing.JTextField();
		GenderPanel = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		textGender = new javax.swing.JComboBox<>();
		BloodTypePanel = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		bloodText = new javax.swing.JComboBox<>();
		InsuranceTypePanel = new javax.swing.JPanel();
		jLabel16 = new javax.swing.JLabel();
		healthText = new javax.swing.JComboBox<>();
		InsuranceTakerPanel = new javax.swing.JPanel();
		jLabel17 = new javax.swing.JLabel();
		takerText = new javax.swing.JTextField();
		BillPanel = new javax.swing.JPanel();
		jLabel18 = new javax.swing.JLabel();
		billText = new javax.swing.JTextField();
		ButtonsPanel = new javax.swing.JPanel();
		cancel = new misc.RSButtonMetro();
		save = new misc.RSButtonMetro();

		setLayout(new java.awt.BorderLayout());

		NorthPanel.setLayout(new javax.swing.BoxLayout(NorthPanel, javax.swing.BoxLayout.Y_AXIS));

		LabelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		jLabel1.setText("Select a doctor");
		LabelPanel.add(jLabel1);

		NorthPanel.add(LabelPanel);

		patientComboBox.setModel(new DefaultComboBoxModel<>(patientList));

		ComboBoxPanel.add(patientComboBox);

		NorthPanel.add(ComboBoxPanel);

		buttonUpdate.setText("Update");
		buttonUpdate.setColorHover(new java.awt.Color(138, 202, 234));
		buttonUpdate.setColorNormal(new java.awt.Color(8, 72, 135));
		buttonUpdate.setColorPressed(new java.awt.Color(8, 72, 135));
		buttonUpdate.setColorTextHover(new java.awt.Color(51, 51, 51));
		buttonUpdate.setColorTextNormal(new java.awt.Color(242, 242, 242));
		buttonUpdate.setColorTextPressed(new java.awt.Color(242, 242, 242));
		buttonUpdate.setFocusPainted(false);
		buttonUpdate.setRolloverEnabled(false);
		buttonUpdate.setRolloverEnabled(false);
		buttonUpdate.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				buttonUpdateActionPerformed(e);
			}
		});
		ButtonUpdatePanel.add(buttonUpdate);

		NorthPanel.add(ButtonUpdatePanel);

		add(NorthPanel, java.awt.BorderLayout.PAGE_START);

		CenterPanel.setLayout(new javax.swing.BoxLayout(CenterPanel, javax.swing.BoxLayout.Y_AXIS));

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(51, 51, 51));
		jLabel10.setText("Name: ");
		NamePanel.add(jLabel10);

		textName.setText("jTextField1");
		textName.setPreferredSize(new Dimension(60, 20));
		NamePanel.add(textName);

		CenterPanel.add(NamePanel);

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(51, 51, 51));
		jLabel11.setText("Last Name: ");
		LastNamePanel.add(jLabel11);

		textLastName.setText("jTextField1");
		textLastName.setPreferredSize(new Dimension(60, 20));
		LastNamePanel.add(textLastName);

		CenterPanel.add(LastNamePanel);

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(51, 51, 51));
		jLabel12.setText("Birth Date: ");
		BithDatePanel.add(jLabel12);

		textBDay.setText("jTextField1");
		textBDay.setPreferredSize(new Dimension(80, 20));
		BithDatePanel.add(textBDay);

		CenterPanel.add(BithDatePanel);

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(51, 51, 51));
		jLabel13.setText("Email: ");
		EmailPanel.add(jLabel13);

		textemail.setText("jTextField1");
		textemail.setPreferredSize(new Dimension(120, 20));
		EmailPanel.add(textemail);

		CenterPanel.add(EmailPanel);

		jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(51, 51, 51));
		jLabel19.setText("Phone: ");
		EmailPanel1.add(jLabel19);

		textPhone.setText("jTextField1");
		textPhone.setPreferredSize(new Dimension(60, 20));
		EmailPanel1.add(textPhone);

		CenterPanel.add(EmailPanel1);

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(51, 51, 51));
		jLabel14.setText("Gender: ");
		GenderPanel.add(jLabel14);

		textGender.setModel(new javax.swing.DefaultComboBoxModel<>(Gender.values()));
		GenderPanel.add(textGender);

		CenterPanel.add(GenderPanel);

		jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(51, 51, 51));
		jLabel15.setText("Blood Type: ");
		BloodTypePanel.add(jLabel15);

		bloodText.setModel(new javax.swing.DefaultComboBoxModel<>(BloodType.values()));
		BloodTypePanel.add(bloodText);

		CenterPanel.add(BloodTypePanel);

		jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(51, 51, 51));
		jLabel16.setText("Insurance Type: ");
		InsuranceTypePanel.add(jLabel16);

		healthText.setModel(new javax.swing.DefaultComboBoxModel<>(HealthInsuranceType.values()));
		InsuranceTypePanel.add(healthText);

		CenterPanel.add(InsuranceTypePanel);

		jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel17.setForeground(new java.awt.Color(51, 51, 51));
		jLabel17.setText("Insurance Taker: ");
		InsuranceTakerPanel.add(jLabel17);

		takerText.setText("jTextField1");
		takerText.setPreferredSize(new Dimension(60, 20));
		InsuranceTakerPanel.add(takerText);

		CenterPanel.add(InsuranceTakerPanel);

		jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(51, 51, 51));
		jLabel18.setText("Bill");
		BillPanel.add(jLabel18);

		billText.setText("jTextField1");
		billText.setPreferredSize(new Dimension(60, 20));
		BillPanel.add(billText);

		CenterPanel.add(BillPanel);

		cancel.setText("Cancel");
		cancel.setColorHover(new java.awt.Color(138, 202, 234));
		cancel.setColorNormal(new java.awt.Color(8, 72, 135));
		cancel.setColorPressed(new java.awt.Color(8, 72, 135));
		cancel.setColorTextHover(new java.awt.Color(51, 51, 51));
		cancel.setColorTextNormal(new java.awt.Color(242, 242, 242));
		cancel.setColorTextPressed(new java.awt.Color(242, 242, 242));
		cancel.setFocusPainted(false);
		cancel.setRolloverEnabled(false);
		cancel.setRolloverEnabled(false);
		cancel.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				cancelActionPerformed(e);
			}
		});

		ButtonsPanel.add(cancel);

		save.setText("Save");
		save.setColorHover(new java.awt.Color(138, 202, 234));
		save.setColorNormal(new java.awt.Color(8, 72, 135));
		save.setColorPressed(new java.awt.Color(8, 72, 135));
		save.setColorTextHover(new java.awt.Color(51, 51, 51));
		save.setColorTextNormal(new java.awt.Color(242, 242, 242));
		save.setColorTextPressed(new java.awt.Color(242, 242, 242));
		save.setFocusPainted(false);
		save.setRolloverEnabled(false);
		save.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				commitActionPerformed(e);
			}
		});
		ButtonsPanel.add(save);

		CenterPanel.add(ButtonsPanel);

		add(CenterPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>

	private void buttonUpdateActionPerformed(ActionEvent e) {
		open();
	}

	private void cancelActionPerformed(ActionEvent e) {
	}

	private void commitActionPerformed(ActionEvent e) {
		List<String> colData = getIntroducedData();
		if (colData.size() != 11) {
			JOptionPane.showMessageDialog(null, "Not enough arguments",
					"Error on data collection", JOptionPane.ERROR_MESSAGE);
		}
		else {
			try {
				ctrl.updatePatient(colData);
				JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Changes were saved sucessfully","", JOptionPane.INFORMATION_MESSAGE);
			} catch (SQLException e1) {
				JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), e1.getMessage(),"Error on Query", JOptionPane.ERROR_MESSAGE);
				if (Main.SHOW_EXCEPTIONS_TRACE)
					e1.printStackTrace();
			}
		}

	}

	@SuppressWarnings("finally")
	public List<String> getIntroducedData(){
		ArrayList<String> data = new ArrayList<String>();
		try {
			data.add(patient.getDni());
			data.add(textLastName.getText());
			data.add(textName.getText());
			data.add(textBDay.getText());
			data.add(textemail.getText());
			data.add(textPhone.getText());
			data.add(textGender.getSelectedItem().toString());
			data.add(bloodText.getSelectedItem().toString());
			data.add(healthText.getSelectedItem().toString());
			try {
				data.add(takerText.getText());
			}
			catch (NullPointerException e1) {
				data.add(patient.getDni());
			}
			try {
				data.add(billText.getText());
			}
			catch (NullPointerException e1) {
				data.add("0");
			}
		}
		catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getMessage(),
					"Error on data collection", JOptionPane.ERROR_MESSAGE);

			if (Main.SHOW_EXCEPTIONS_TRACE)
				e.printStackTrace();
		}
		finally{
			return data;
		}
	}


	// Variables declaration - do not modify
	private javax.swing.JPanel BillPanel;
	private javax.swing.JPanel BithDatePanel;
	private javax.swing.JPanel BloodTypePanel;
	private misc.RSButtonMetro buttonUpdate;
	private javax.swing.JPanel ButtonUpdatePanel;
	private javax.swing.JPanel ButtonsPanel;
	private javax.swing.JPanel CenterPanel;
	private javax.swing.JPanel ComboBoxPanel;
	private javax.swing.JPanel EmailPanel;
	private javax.swing.JPanel EmailPanel1;
	private javax.swing.JPanel GenderPanel;
	private javax.swing.JPanel InsuranceTakerPanel;
	private javax.swing.JPanel InsuranceTypePanel;
	private javax.swing.JPanel LabelPanel;
	private javax.swing.JPanel LastNamePanel;
	private javax.swing.JPanel NamePanel;
	private javax.swing.JPanel NorthPanel;
	private misc.RSButtonMetro cancel;
	private misc.RSButtonMetro save;
	private javax.swing.JComboBox<Patient> patientComboBox;
	private javax.swing.JComboBox<Gender> textGender;
	private javax.swing.JComboBox<BloodType> bloodText;
	private javax.swing.JComboBox<HealthInsuranceType> healthText;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JTextField billText;
	private javax.swing.JTextField textName;
	private javax.swing.JTextField textLastName;
	private javax.swing.JTextField textBDay;
	private javax.swing.JTextField textemail;
	private javax.swing.JTextField textPhone;
	private javax.swing.JTextField takerText;
	// End of variables declaration
}