/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer.doctor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingUtilities;

import control.Controller;
import launcher.Main;
import model.Patient;
import model.Treatment;

/**
 *
 * @author reven
 */
public class AddTreatmentDialog extends javax.swing.JDialog {

	private Controller ctrl;
	private Patient patient;

	/**
	 * Creates new form AddTreatmentWindow
	 */
	public AddTreatmentDialog(Controller ctrl, Patient patient, JComponent parent) {
		this.ctrl = ctrl;
		this.patient = patient;

		initComponents();
		setLocationRelativeTo(parent);

		Calendar cal = Calendar.getInstance(Locale.FRANCE);
		((SpinnerDateModel) endSpinner.getModel()).setStart(cal.getTime());
		cal.add(Calendar.MONTH, 1);
		endSpinner.getModel().setValue(cal.getTime());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		centerPanel = new javax.swing.JPanel();
		row1Panel = new javax.swing.JPanel();
		nameLabel = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		nameTextField = new javax.swing.JTextField();
		row2Panel = new javax.swing.JPanel();
		descLabel = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jScrollPane1 = new javax.swing.JScrollPane();
		descTextArea = new javax.swing.JTextArea();
		row3Panel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		startDatePanel = new javax.swing.JPanel();
		startSpinner = new javax.swing.JSpinner();
		endDatePanel = new javax.swing.JPanel();
		endSpinner = new javax.swing.JSpinner();
		bottomPanel = new javax.swing.JPanel();
		cancelButton = new misc.RSButtonMetro();
		saveButton = new misc.RSButtonMetro();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(400, 300));
		setPreferredSize(new java.awt.Dimension(400, 500));
		setModal(true);


		centerPanel.setLayout(new java.awt.GridLayout(3, 1));

		row1Panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		row1Panel.setLayout(new javax.swing.BoxLayout(row1Panel, javax.swing.BoxLayout.LINE_AXIS));

		nameLabel.setText("Treatment name");
		row1Panel.add(nameLabel);

		jSeparator1.setForeground(new java.awt.Color(242, 242, 242));
		jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 30));
		jSeparator1.setMinimumSize(new java.awt.Dimension(10, 10));
		jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
		row1Panel.add(jSeparator1);

		nameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 29));
		row1Panel.add(nameTextField);

		centerPanel.add(row1Panel);

		row2Panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		row2Panel.setLayout(new javax.swing.BoxLayout(row2Panel, javax.swing.BoxLayout.LINE_AXIS));

		descLabel.setText("Desciption");
		row2Panel.add(descLabel);

		jSeparator2.setForeground(new java.awt.Color(242, 242, 242));
		jSeparator2.setMaximumSize(new java.awt.Dimension(10, 30));
		jSeparator2.setPreferredSize(new java.awt.Dimension(10, 10));
		row2Panel.add(jSeparator2);

		descTextArea.setColumns(20);
		descTextArea.setRows(5);
		jScrollPane1.setViewportView(descTextArea);

		row2Panel.add(jScrollPane1);

		centerPanel.add(row2Panel);

		row3Panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		row3Panel.setLayout(new java.awt.GridLayout(2, 2, 10, 0));

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Start date");
		jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		row3Panel.add(jLabel1);

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("End date");
		jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		row3Panel.add(jLabel2);

		startSpinner.setModel(new javax.swing.SpinnerDateModel());
		startSpinner.setEditor(new javax.swing.JSpinner.DateEditor(startSpinner, "yyyy-MM-dd"));
		startDatePanel.add(startSpinner);

		row3Panel.add(startDatePanel);

		endSpinner.setModel(new javax.swing.SpinnerDateModel());
		endSpinner.setEditor(new javax.swing.JSpinner.DateEditor(endSpinner, "yyyy-MM-dd"));
		endDatePanel.add(endSpinner);

		row3Panel.add(endDatePanel);

		centerPanel.add(row3Panel);

		getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

		bottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

		cancelButton.setText("Cancel");
		cancelButton.setColorHover(new java.awt.Color(138, 202, 234));
		cancelButton.setColorNormal(new java.awt.Color(8, 72, 135));
		cancelButton.setColorPressed(new java.awt.Color(8, 72, 135));
		cancelButton.setColorTextHover(new java.awt.Color(51, 51, 51));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});
		bottomPanel.add(cancelButton);

		saveButton.setText("Save");
		saveButton.setColorHover(new java.awt.Color(138, 202, 234));
		saveButton.setColorNormal(new java.awt.Color(8, 72, 135));
		saveButton.setColorPressed(new java.awt.Color(8, 72, 135));
		saveButton.setColorTextHover(new java.awt.Color(51, 51, 51));
		saveButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				saveButtonActionPerformed(e);
			}
		});
		bottomPanel.add(saveButton);

		getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

		pack();
	}// </editor-fold>


	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	protected void saveButtonActionPerformed(ActionEvent e) {
		Treatment t = new Treatment(
				-1,
				nameTextField.getText(),
				descTextArea.getText(),
				new SimpleDateFormat("yyyy-MM-dd").format(startSpinner.getValue()),
				new SimpleDateFormat("yyyy-MM-dd").format(endSpinner.getValue()));

		try {
			ctrl.saveTreatment(t, patient.getDni());
			JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Treatment was successfully saved", "", JOptionPane.INFORMATION_MESSAGE);
			dispose();
		} catch (SQLException e1) {
			JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), e1.getMessage(), "", JOptionPane.ERROR_MESSAGE);

			if (Main.SHOW_EXCEPTIONS_TRACE)
				e1.printStackTrace();
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel bottomPanel;
	private javax.swing.JPanel centerPanel;
	private javax.swing.JLabel descLabel;
	private javax.swing.JTextArea descTextArea;
	private javax.swing.JPanel endDatePanel;
	private javax.swing.JSpinner endSpinner;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameTextField;
	private misc.RSButtonMetro cancelButton;
	private misc.RSButtonMetro saveButton;
	private javax.swing.JPanel row1Panel;
	private javax.swing.JPanel row2Panel;
	private javax.swing.JPanel row3Panel;
	private javax.swing.JPanel startDatePanel;
	private javax.swing.JSpinner startSpinner;
	// End of variables declaration
}

