/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewer.doctor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import control.Controller;
import model.Patient;

/**
 *
 * @author reven
 */
@SuppressWarnings("serial")
public class MyPatientsPanel extends javax.swing.JPanel {

	private Controller ctrl;
	private String doctor_dni;

	private MyPatientsTableModel tableModel;

	/**
	 * Creates new form MyPatientsPanel
	 */
	public MyPatientsPanel(Controller ctrl, String doctor_dni) {
		this.ctrl = ctrl;
		this.doctor_dni = doctor_dni;
		this.tableModel = new MyPatientsTableModel(ctrl, doctor_dni);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		topPanel = new javax.swing.JPanel();
		titleLabel = new javax.swing.JLabel();
		patientsTableScroll = new javax.swing.JScrollPane();
		patientsTable = new javax.swing.JTable(tableModel);
		bottomPanel = new javax.swing.JPanel();
		viewMedicHistoryButton = new misc.RSButtonMetro();
		addTreatmentButton = new misc.RSButtonMetro();

		setLayout(new java.awt.BorderLayout());

		titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		titleLabel.setForeground(new java.awt.Color(51, 51, 51));
		titleLabel.setText("My Patients");
		topPanel.add(titleLabel);

		add(topPanel, java.awt.BorderLayout.PAGE_START);

		patientsTableScroll.setViewportView(patientsTable);
		add(patientsTableScroll, java.awt.BorderLayout.CENTER);

		viewMedicHistoryButton.setText("View medic history");
		viewMedicHistoryButton.setColorHover(new java.awt.Color(138, 202, 234));
		viewMedicHistoryButton.setColorNormal(new java.awt.Color(8, 72, 135));
		viewMedicHistoryButton.setColorPressed(new java.awt.Color(8, 72, 135));
		viewMedicHistoryButton.setColorTextHover(new java.awt.Color(51, 51, 51));
		viewMedicHistoryButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				viewMedicHistoryButtonActionPerformed(e);
			}
		});

		bottomPanel.add(viewMedicHistoryButton);

		addTreatmentButton.setText("Add Treatment");
		addTreatmentButton.setColorHover(new java.awt.Color(138, 202, 234));
		addTreatmentButton.setColorNormal(new java.awt.Color(8, 72, 135));
		addTreatmentButton.setColorPressed(new java.awt.Color(8, 72, 135));
		addTreatmentButton.setColorTextHover(new java.awt.Color(51, 51, 51));
		addTreatmentButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				addTreatmentButtonActionPerformed(e);
			}

		});

		bottomPanel.add(addTreatmentButton);

		add(bottomPanel, java.awt.BorderLayout.PAGE_END);
	}// </editor-fold>

	private void viewMedicHistoryButtonActionPerformed(ActionEvent e) {
		try {
			Patient p = tableModel.getSelectedPatient(patientsTable.getSelectedRow());
			// TODO panel del historial medico de un paciente p

		} catch (IndexOutOfBoundsException e1) { // no row selected
			JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "You have to select a patient", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void addTreatmentButtonActionPerformed(ActionEvent e) {
		if (patientsTable.getSelectedRow() == -1) { // no row selected
			JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "You have to select a patient", "", JOptionPane.ERROR_MESSAGE);
		}
		else {
			AddTreatmentDialog atd = new AddTreatmentDialog(
					ctrl,
					tableModel.getSelectedPatient(patientsTable.getSelectedRow()),
					this);
			atd.setVisible(true);
		}
	}

	public void open() {
		tableModel.open();
	}


	// Variables declaration - do not modify
	private javax.swing.JPanel bottomPanel;
	private javax.swing.JTable patientsTable;
	private javax.swing.JScrollPane patientsTableScroll;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JPanel topPanel;
	private misc.RSButtonMetro viewMedicHistoryButton;
	private misc.RSButtonMetro addTreatmentButton;
	// End of variables declaration

}
