/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewer.patient;

import java.awt.Color;

import control.Controller;

/**
 *
 * @author reven
 */
public class AppointmentsPanel extends javax.swing.JPanel {

	private Controller ctrl;
	private String dni;

	/**
	 * Creates new form AppointmentsPanel
	 * @param ctrl
	 * @param dni
	 */
	public AppointmentsPanel(Controller ctrl, String dni) {
		this.ctrl = ctrl;
		this.dni = dni;

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "serial" })
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel7 = new javax.swing.JLabel();
		rightPanel = new javax.swing.JPanel();
		calendarPanel1 = new viewer.misc.CalendarPanel();
		centerPanel = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		jLabel7.setText("jLabel7");

		setLayout(new java.awt.BorderLayout());

		rightPanel.setPreferredSize(new java.awt.Dimension(300, 527));

		calendarPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
		calendarPanel1.setMinimumSize(new java.awt.Dimension(600, 150));
		calendarPanel1.setPreferredSize(new java.awt.Dimension(300, 350));
		rightPanel.add(calendarPanel1);

		add(rightPanel, java.awt.BorderLayout.LINE_END);

		centerPanel.setLayout(new java.awt.BorderLayout());

		jTable1 = new javax.swing.JTable(new AppointmentsTableModel(dni));
		jScrollPane2.setViewportView(jTable1);

		centerPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);
		centerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK,5), "My Appointments",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

		add(centerPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>


	// Variables declaration - do not modify
	private viewer.misc.CalendarPanel calendarPanel1;
	private javax.swing.JPanel centerPanel;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel rightPanel;
	// End of variables declaration
}
