/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewer.patient;

/**
 *
 * @author rodri
 */
@SuppressWarnings("serial")
public class PatientHomePanel extends javax.swing.JPanel {

	private static PatientHomePanel instance = null;

	private String name;

	private PatientHomePanel(String name) {
		this.name = name;
		initComponents();
	}

	// Singleton
	public static PatientHomePanel getInstance(String name) {
		if (instance == null)
			instance = new PatientHomePanel(name);

		return instance;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		northPanel = new javax.swing.JPanel();
		labelWelcome = new javax.swing.JLabel();
		centerPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setForeground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(760, 527));
		setLayout(new java.awt.BorderLayout());

		//NorthPanel.setBackground(new java.awt.Color(216, 216, 216));
		northPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 10, 1));
		northPanel.setForeground(new java.awt.Color(255, 255, 255));
		northPanel.setPreferredSize(new java.awt.Dimension(760, 150));
		northPanel.setRequestFocusEnabled(false);

		labelWelcome.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
		labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelWelcome.setText(String.format("<html>WELCOME %s</html>", name));
		labelWelcome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
		labelWelcome.setMinimumSize(new java.awt.Dimension(637, 160));
		labelWelcome.setName(""); // NOI18N
		labelWelcome.setPreferredSize(new java.awt.Dimension(700, 150));
		northPanel.add(labelWelcome);

		add(northPanel, java.awt.BorderLayout.PAGE_START);

		//CenterPanel.setBackground(new java.awt.Color(216, 216, 216));
		centerPanel.setMinimumSize(new java.awt.Dimension(760, 317));
		centerPanel.setPreferredSize(new java.awt.Dimension(760, 317));

		jLabel1.setIcon(new javax.swing.ImageIcon("resources/HomeImages/CentroDeSalud.png")); // NOI18N
		centerPanel.add(jLabel1);

		add(centerPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>


	// Variables declaration - do not modify
	private javax.swing.JPanel centerPanel;
	private javax.swing.JLabel labelWelcome;
	private javax.swing.JPanel northPanel;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration
}
