/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewer.patient;

/**
 *
 * @author reven
 */
public class ProfilePanel extends javax.swing.JPanel {

	/**
	 * Creates new form ProfilePanel
	 */
	public ProfilePanel() {
		initComponents();
		birthSpinner.setEditor(new javax.swing.JSpinner.DateEditor(birthSpinner, "yyyy-MM-dd"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		genderButtonGroup = new javax.swing.ButtonGroup();
		topPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		centerPanel = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		nameField = new javax.swing.JTextField();
		lastnameField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		passField = new javax.swing.JTextField();
		birthPanel = new javax.swing.JPanel();
		birthSpinner = new javax.swing.JSpinner();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		emailField = new javax.swing.JTextField();
		phoneField = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		genderPanel = new javax.swing.JPanel();
		maleButton = new javax.swing.JRadioButton();
		femaleButton = new javax.swing.JRadioButton();
		bloodPanel = new javax.swing.JPanel();
		bloodComboBox = new javax.swing.JComboBox<>();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		ibanField = new javax.swing.JTextField();
		addressField = new javax.swing.JTextField();
		bottomPanel = new javax.swing.JPanel();
		saveButton = new misc.RSButtonMetro();

		setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
		setLayout(new java.awt.BorderLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(51, 51, 51));
		jLabel1.setText("Modify your profile information");
		topPanel.add(jLabel1);

		add(topPanel, java.awt.BorderLayout.PAGE_START);

		centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		centerPanel.setLayout(new java.awt.GridLayout(10, 2, 10, 10));

		jLabel2.setText("Name");
		jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel2);

		jLabel3.setText("Lastname");
		jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel3);

		nameField.setText("name");
		nameField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		nameField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameFieldActionPerformed(evt);
			}
		});
		centerPanel.add(nameField);

		lastnameField.setText("lastname");
		lastnameField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		centerPanel.add(lastnameField);

		jLabel4.setText("Password");
		jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel4);

		jLabel5.setText("Birthdate");
		jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel5);

		passField.setText("pass");
		passField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		centerPanel.add(passField);

		birthPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		birthPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		birthSpinner.setModel(new javax.swing.SpinnerDateModel());
		birthPanel.add(birthSpinner);

		centerPanel.add(birthPanel);

		jLabel6.setText("Email");
		jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel6);

		jLabel7.setText("Phone");
		jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel7);

		emailField.setText("email");
		emailField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		emailField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				emailFieldActionPerformed(evt);
			}
		});
		centerPanel.add(emailField);

		phoneField.setText("phone");
		phoneField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		centerPanel.add(phoneField);

		jLabel8.setText("Gender");
		jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel8);

		jLabel9.setText("Blood type");
		jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel9);

		genderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		genderButtonGroup.add(maleButton);
		maleButton.setText("Male");
		genderPanel.add(maleButton);

		genderButtonGroup.add(femaleButton);
		femaleButton.setText("Female");
		femaleButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				femaleButtonActionPerformed(evt);
			}
		});
		genderPanel.add(femaleButton);

		centerPanel.add(genderPanel);

		bloodPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		bloodPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		bloodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		bloodPanel.add(bloodComboBox);

		centerPanel.add(bloodPanel);

		jLabel10.setText("IBAN");
		jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel10);

		jLabel11.setText("Home address");
		jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		centerPanel.add(jLabel11);

		ibanField.setText("iban");
		ibanField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		ibanField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ibanFieldActionPerformed(evt);
			}
		});
		centerPanel.add(ibanField);

		addressField.setText("address");
		addressField.setMargin(new java.awt.Insets(2, 7, 2, 6));
		centerPanel.add(addressField);

		add(centerPanel, java.awt.BorderLayout.CENTER);

		saveButton.setText("Save changes");
		saveButton.setColorHover(new java.awt.Color(138, 202, 234));
		saveButton.setColorNormal(new java.awt.Color(8, 72, 135));
		saveButton.setColorPressed(new java.awt.Color(8, 72, 135));
		saveButton.setColorTextHover(new java.awt.Color(51, 51, 51));
		bottomPanel.add(saveButton);

		add(bottomPanel, java.awt.BorderLayout.PAGE_END);
	}// </editor-fold>

	private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void ibanFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	public void open() {
		// TODO consultas sql para leer los datos de perfil
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField addressField;
	private javax.swing.JPanel birthPanel;
	private javax.swing.JSpinner birthSpinner;
	private javax.swing.JComboBox<String> bloodComboBox;
	private javax.swing.JPanel bloodPanel;
	private javax.swing.JPanel bottomPanel;
	private javax.swing.JPanel centerPanel;
	private javax.swing.JTextField emailField;
	private javax.swing.JRadioButton femaleButton;
	private javax.swing.ButtonGroup genderButtonGroup;
	private javax.swing.JPanel genderPanel;
	private javax.swing.JTextField ibanField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField lastnameField;
	private javax.swing.JRadioButton maleButton;
	private javax.swing.JTextField nameField;
	private javax.swing.JTextField passField;
	private javax.swing.JTextField phoneField;
	private misc.RSButtonMetro saveButton;
	private javax.swing.JPanel topPanel;
	// End of variables declaration

}

